#!/usr/bin/env python3
# ==========================================================================
# Taylor AI Platform — unified runtime secrets  (v1.1.8)
# ==========================================================================
# ONE resolver, ONE derived runtime env file, sourced by the gateway wrapper.
#
# THE BUG THIS FIXES
#   The gateway failed with "Primary provider auth failed: No Anthropic
#   credentials found." while `op read` for the same reference succeeded from a
#   shell. Both facts were true at once:
#
#     - config.yaml maps ANTHROPIC_API_KEY -> op://Hermes/... (21 refs total)
#     - config.yaml keeps secrets.onepassword.enabled FALSE on purpose,
#       because enabling it makes Hermes resolve all 21 at startup — sequential
#       `op read` calls, /dev/tty prompts, cold-start stalls, MCP timeouts
#     - gateway-run.sh sourced only /root/.env and ~/.hermes/.env
#
#   So a key that lived ONLY in the vault never reached the gateway process.
#   COMPOSIO_API_KEY was the sole exception, because v1.1.2 gave it — and only
#   it — a derived runtime env file. This generalises that proven fix to every
#   declared runtime secret, and to nothing else: the 16 references the runtime
#   does not need are still not resolved at startup.
#
#   nicks-stack-secrets render     resolve declared secrets -> 0600 env file
#   nicks-stack-secrets status     presence only, never values
#   nicks-stack-secrets clean      remove the derived file
#
# SECRET SAFETY
#   Values are written to one 0600 root-owned file and nowhere else. This
#   script never prints a value, prefix, length, hash or excerpt; `status`
#   reports state words only. Rendering is atomic and FAILS CLOSED: if a
#   required secret cannot be resolved the file is removed rather than left
#   partial, so the gateway can never source a half-populated environment.
# ==========================================================================
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lib  # noqa: E402


def _purge_plaintext_caches(spec: dict) -> list[str]:
    """Remove Hermes' plaintext op:// value caches.

    Hermes writes resolved secret VALUES to cache/op_cache.json when it does
    its own 1Password resolution. The platform never enables that, but a stale
    file can survive from an earlier run or an experiment. It is Hermes-owned
    and regenerated on demand, so removing it loses nothing and stops provider
    credentials persisting in plaintext json."""
    removed = []
    for path in spec["purge"]:
        try:
            if path.is_file():
                path.unlink()
                removed.append(str(path))
        except OSError:
            pass
    return removed


def render(quiet: bool = False) -> int:
    """Resolve every declared runtime secret into the derived 0600 env file."""
    spec = lib.runtime_secrets_spec()
    target = Path(spec["dir"]) / spec["file"]
    if not spec["keys"]:
        print("secrets: platform.yaml declares no runtime_secrets — nothing to do",
              file=sys.stderr)
        return 1

    resolved, missing_required, optional_absent = {}, [], []
    for entry in spec["keys"]:
        res = lib.resolve_runtime_secret(entry["env"])
        if res["available"]:
            resolved[entry["env"]] = res["value"]
        elif entry["required"]:
            missing_required.append(f"{entry['env']} ({res['error']})")
        else:
            optional_absent.append(entry["env"])

    if missing_required:
        # FAIL CLOSED. A partial file is worse than none: the gateway would
        # start, authenticate nothing, and report a confusing downstream error.
        try:
            if target.is_file():
                target.unlink()
        except OSError:
            pass
        for line in missing_required:
            print(f"secrets: REQUIRED {line}", file=sys.stderr)
        print(f"secrets: refusing to write a partial {target} — the gateway would "
              f"start without credentials it needs", file=sys.stderr)
        return 1

    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        os.chmod(target.parent, 0o700)
        tmp = target.with_suffix(".tmp")
        # 0600 BEFORE any secret reaches the file.
        tmp.touch(mode=0o600, exist_ok=True)
        os.chmod(tmp, 0o600)
        body = [
            "# Generated by secrets_runtime.py — DERIVED and SECRET-BEARING.",
            "# Do not edit, do not commit, do not print. Mode 0600, root-owned.",
            "# Sourced by hermes-gateway-run.sh. Rebuilt on every gateway start.",
        ]
        body += [f"{k}={v}" for k, v in resolved.items()]
        tmp.write_text("\n".join(body) + "\n")
        os.chmod(tmp, 0o600)
        tmp.replace(target)
        os.chmod(target, 0o600)
    except OSError as exc:
        try:
            if target.is_file():
                target.unlink()
        except OSError:
            pass
        print(f"secrets: could not write {target}: {exc}", file=sys.stderr)
        return 1

    purged = _purge_plaintext_caches(spec)
    if not quiet:
        # Counts and names only — never a value.
        print(f"secrets: {len(resolved)} runtime secret(s) resolved into {target} (0600)"
              + (f", {len(optional_absent)} optional absent: {', '.join(optional_absent)}"
                 if optional_absent else ""))
        if purged:
            print(f"secrets: purged plaintext cache(s): {', '.join(purged)}")
    return 0


def cmd_render(args) -> int:
    return render(quiet=args.quiet)


def cmd_clean(args) -> int:
    target = lib.runtime_secrets_path()
    try:
        if target.is_file():
            target.unlink()
            print(f"secrets: removed {target}")
        else:
            print(f"secrets: {target} not present")
    except OSError as exc:
        print(f"secrets: could not remove {target}: {exc}", file=sys.stderr)
        return 1
    return 0


def cmd_status(args) -> int:
    report = lib.runtime_secrets_report()
    if args.json:
        print(json.dumps(report, indent=2, ensure_ascii=False))
        return 0 if (report["ok"] and report["gateway_ready"]) else 1

    tick = lambda ok: "✓" if ok else "✗"  # noqa: E731
    print("Runtime secrets")
    print("─" * 20)
    width = max((len(k["key"]) for k in report["keys"]), default=20)
    for k in report["keys"]:
        if k["available"]:
            state = f"resolved from {k['source']}"
        elif not k["required"]:
            state = "optional, absent"
        else:
            state = "NOT RESOLVED"
        mark = tick(k["available"]) if k["required"] else ("✓" if k["available"] else "○")
        print(f"  {mark} {k['key']:<{width}}  {state}")
        if not k["available"] and k["required"]:
            print(f"      └ {k['error']}")
    print()
    print(f"Runtime env   {tick(report['exists'])} {report['path']}"
          f"{'' if report['exists'] else '  (not rendered yet)'}")
    if report["exists"]:
        print(f"Mode          {tick(report['mode_ok'])} {report['mode'] or 'unknown'}"
              f"{'' if report['mode_ok'] else '  EXPECTED 0600'}")
    print(f"Gateway ready {tick(report['gateway_ready'])} "
          f"{'every required secret is in the runtime env' if report['gateway_ready'] else 'the gateway would start WITHOUT a required secret — run: sudo nicks-stack-secrets render'}")
    print("\n(no secret value, prefix, length or hash is ever printed)")
    return 0 if (report["ok"] and report["gateway_ready"]) else 1


def main() -> int:
    ap = argparse.ArgumentParser(
        prog="secrets_runtime.py",
        description="Unified runtime secret resolution for the Hermes gateway")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("render", help="resolve declared secrets into the 0600 runtime env")
    p.add_argument("--quiet", action="store_true")
    p = sub.add_parser("status", help="presence-only report (never values)")
    p.add_argument("--json", action="store_true")
    sub.add_parser("clean", help="remove the derived runtime env")
    args = ap.parse_args()
    return {"render": cmd_render, "status": cmd_status, "clean": cmd_clean}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
